Feat/home#2
coclassproject/Godting_front pull request #5
Opened 2022-03-21 06:16 UTC by Duck-98

main 완성

2022-03-21 06:45 UTC, JhsK requested changes
색상, float 부분만 수정해서 푸쉬 한번 더 부탁행

2022-03-21 06:45 UTC, JhsK commented on src/components/home/Category.tsx
> +  float: right;
float는 가능하면 최대한 기피해주고 다른 방식으로 정렬하는 식으로 부탁행

2022-03-21 06:45 UTC, JhsK commented on src/components/home/Card.tsx
> +  border: 1px solid #f5f5f5;
background-color, color, border의 color 등 색상이 들어가는 곳은 props theme 값으로 글로벌 변수 가져와서 설정해주고 만약 원하는 색상이 없으면 너가 추가 해주는 식으로 부탁행

2022-03-22 08:55 UTC, Duck-98 commented on src/components/home/Category.tsx
> +  float: right;
"완료"

2022-03-22 09:20 UTC, Duck-98 commented on src/components/home/Card.tsx
> +  border: 1px solid #f5f5f5;
나안해

2022-03-22 09:35 UTC, JhsK approved these changes

2022-03-22 09:35 UTC, merged